### ISSUE TITLE
Adding parameters to the request along with Includes

### ISSUE THREAD

**Issue by ils-rahulm** [hristonev/SportMonks-Client-Bundle#14]
While trying to include parameters such as league_id in the fixture by date along with include, it doesn't give requested data.

**Comment by hristonev** [comment]
There is no include league_id, You can include league as well.

**Comment by ils-rahulm** [comment]
I was trying to get specific league data, Unfortunately, was doing it all wrong.

I am now able to get that working using this

`$matches = $client->fixtures()->date()->day(
			$date_object,
			[
				'query' => [
					'include' => 'localTeam,visitorTeam',
					'leagues' => $league_id
				],
			]);`
